[package]
name = "sparv-kbner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sparv_kbner"
crate-type = ["cdylib"]

[dependencies]
log = "0.4.17"
pyo3 = "0.18.1"
pyo3-log = "0.8.1"
