metadata:
    id: 8sidor-kbner
    language: swe

import:
    text_annotation: text
    importer: xml_import:parse

xml_import:
    elements:
        - p

xml_export:
    annotations:
        - <sentence>
        - <paragraph>
        - <token:word>
        - <token>:stanza.pos
        - <token>:sparv_kbner.ne_type
        - <token>:sparv_kbner.ne_score

classes:
    paragraph: p
sparv:
    compression: none
